import Head from "next/head"
import apolloClient from "../apolloClient"
import { gql } from "@apollo/client"
import Locations from "../comp/Locations"

export const getStaticProps = async () => {
  const { data } = await apolloClient.query({
    query: gql`
      query getLocations {
        locations {
          id
          name
          description
          photo
        }
      }
    `
  })

  return {
    props: {
      locations: data.locations
    }
  }
}

const HomePage = ({ locations }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>A demo from apollographql.com</div>
      <Locations locations={locations} />
    </>
  )
}

export default HomePage
